name: diffbir
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - git
  - curl
  - wget
  - pip:
    - torch==2.2.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.17.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
    - torchaudio==2.2.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
    - xformers==0.0.25.post1
    - omegaconf==2.3.0
    - accelerate==0.28.0
    - einops==0.7.0
    - opencv-python==4.9.0.80
    - scipy==1.12.0
    - ftfy==6.2.0
    - regex==2023.12.25
    - python-dateutil==2.9.0.post0
    - timm==0.9.16
    - pytorch-lightning==2.2.1
    - tensorboard==2.16.2
    - protobuf==4.25.3
    - lpips==0.1.4
    - facexlib==0.3.0
    - gradio
    - polars==1.12.0
    - torchsde==0.2.6
    - bitsandbytes==0.44.1
    - transformers==4.37.2
    - tokenizers==0.15.1
    - sentencepiece==0.1.99
    - fairscale==0.4.4